#第三方登录信息
Client_id: 8002259c435d04d1fb41
Client_secret: 7092f2d3e20908e59bdc9dae0c7c33e8f1b5a0b9
Redirect_uri: http://localhost:8080/callback
#数据库连接
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

